# Generated by Django 4.2.17 on 2025-01-04 10:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('earthquake_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='earthquake',
            name='status',
            field=models.CharField(choices=[('alert', 'Alert'), ('warning', 'Warning'), ('safe', 'Safe')], default='safe', max_length=10),
        ),
    ]
